version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - .:/code
      - ./static:/static
    depends_on:
      - krsnaus
  db:
    image: postgres
    environment:
      - POSTGRES_DB=krsna_us
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=swordfish
  krsnaus:
    build: .
    command: ./start.sh
    volumes:
      - .:/code
      - ./static:/static
    expose:
      - "8000"
    depends_on:
      - db