version: '3'

services:
  nginx:
    image: nginx:latest
    expose:
      - "8001"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    environment:
      - VIRTUAL_HOST=static.gvparchives.com
      - VIRTUAL_PORT=8001
      - LETSENCRYPT_HOST=static.gvparchives.com
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  krsnaus:
    environment:
      - PYTHONUNBUFFERED=0
      - VIRTUAL_HOST=www.gvparchives.com,gvparchives.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=www.gvparchives.com,gvparchives.com
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}    

networks:
  default:
    external:
      name: webproxy
