version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=krsna_us
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=swordfish
  krsnaus:
    build: .
    command: ./start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db