version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
    env_file:
      - ./.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  krsnaus:
    build: .
    command: ./start.sh
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - .:/KrsnaUs
      - ./static:/static
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch

volumes:
  esdata:
  postgres_data:
