# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='harikathacollection',
            unique_together=set([('title', 'link', 'issue')]),
        ),
    ]
