# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0002_auto_20171018_1857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='harikathacollection',
            unique_together=set([]),
        ),
    ]
