# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0004_auto_20171018_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harikathacollection',
            options={'ordering': ['category']},
        ),
    ]
