# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0006_harikathacollection_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harikathacollection',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
