# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0007_auto_20171215_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harikathacollection',
            name='item_id',
        ),
    ]
