# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0010_playlists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlists',
            old_name='item_id',
            new_name='playlist_id',
        ),
        migrations.AddField(
            model_name='playlists',
            name='name',
            field=models.TextField(default='no name'),
            preserve_default=False,
        ),
    ]
