# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0011_auto_20180208_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
