# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0014_playlistitem_item_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistitem',
            options={'ordering': ['item_order']},
        ),
        migrations.AlterModelOptions(
            name='playlists',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together=set([('playlist', 'collection_item')]),
        ),
    ]
