# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0015_auto_20180221_1305'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='harikathacollection',
            unique_together=set([('title', 'link'), ('title', 'link', 'issue')]),
        ),
    ]
