# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0016_auto_20180302_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harikathacollection',
            name='directory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='harikathacollection',
            name='issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='harikathacollection',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='harikathacollection',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
