# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0017_auto_20180304_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harikathacollection',
            options={'ordering': ['category'], 'permissions': (('write_books', 'Write books'), ('write_movies', 'Write movies'), ('write_bhagavatpatrika', 'Write Bhagavat Patrika'), ('write_harmonistmonthly', 'Write Harmonist Monthly'), ('write_harmonistmagazine', 'Write Harmonist Magazine'), ('write_harikatha', 'Write Hari Katha'), ('write_songs', 'Write songs'), ('write_lectures', 'Write lectures'))},
        ),
    ]
