# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0018_auto_20180304_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harikathacollection',
            options={'ordering': ['category'], 'permissions': (('write_book', 'Write books'), ('write_movie', 'Write movies'), ('write_bhagavatpatrika', 'Write Bhagavat Patrika'), ('write_harmonistmonthly', 'Write Harmonist Monthly'), ('write_harmonistmagazine', 'Write Harmonist Magazine'), ('write_harikatha', 'Write Hari Katha'), ('write_song', 'Write songs'), ('write_lecture', 'Write lectures'))},
        ),
    ]
