# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0019_auto_20180305_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harikathacollection',
            name='title',
            field=models.TextField(),
        ),
    ]
