# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harikatha', '0020_auto_20180424_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harikathacollection',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
